#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

typedef struct { const char *name; unsigned char *data; size_t size; uint32_t crc, offset; } entry_t;
static uint32_t crc32_bytes(const unsigned char *p,size_t n){uint32_t c=~0u;for(size_t i=0;i<n;i++){c^=p[i];for(int k=0;k<8;k++)c=(c>>1)^(0xedb88320u&-(int)(c&1));}return~c;}
static void u16(FILE*f,uint16_t v){fputc(v&255,f);fputc(v>>8,f);}static void u32(FILE*f,uint32_t v){u16(f,v&65535);u16(f,v>>16);}
static unsigned char*npy(const char*descr,int fortran,int rank,const size_t*shape,const void*data,size_t bytes,size_t*out){
  char dims[256]="",one[48];for(int i=0;i<rank;i++){snprintf(one,sizeof one,"%zu%s",shape[i],rank==1?",":"");strcat(dims,one);if(i+1<rank)strcat(dims,", ");}
  char dict[512];snprintf(dict,sizeof dict,"{'descr': '%s', 'fortran_order': %s, 'shape': (%s), }",descr,fortran?"True":"False",dims);
  size_t h=strlen(dict)+1;while((10+h)%64)h++;size_t total=10+h+bytes;unsigned char*b=calloc(1,total);if(!b)return NULL;
  memcpy(b,"\x93NUMPY",6);b[6]=1;b[7]=0;b[8]=h&255;b[9]=(h>>8)&255;memcpy(b+10,dict,strlen(dict));memset(b+10+strlen(dict),' ',h-strlen(dict));b[10+h-1]='\n';memcpy(b+10+h,data,bytes);*out=total;return b;
}
static int zip_store(const char*path,entry_t*e,int n){FILE*f=fopen(path,"wb");if(!f)return 1;for(int i=0;i<n;i++){e[i].offset=(uint32_t)ftell(f);e[i].crc=crc32_bytes(e[i].data,e[i].size);u32(f,0x04034b50);u16(f,20);u16(f,0);u16(f,0);u16(f,0);u16(f,0);u32(f,e[i].crc);u32(f,e[i].size);u32(f,e[i].size);u16(f,strlen(e[i].name));u16(f,0);fwrite(e[i].name,1,strlen(e[i].name),f);fwrite(e[i].data,1,e[i].size,f);}uint32_t central=(uint32_t)ftell(f);for(int i=0;i<n;i++){u32(f,0x02014b50);u16(f,20);u16(f,20);u16(f,0);u16(f,0);u16(f,0);u16(f,0);u32(f,e[i].crc);u32(f,e[i].size);u32(f,e[i].size);u16(f,strlen(e[i].name));u16(f,0);u16(f,0);u16(f,0);u16(f,0);u32(f,0);u32(f,e[i].offset);fwrite(e[i].name,1,strlen(e[i].name),f);}uint32_t end=(uint32_t)ftell(f);u32(f,0x06054b50);u16(f,0);u16(f,0);u16(f,n);u16(f,n);u32(f,end-central);u32(f,central);u16(f,0);int rc=fclose(f);return rc!=0;}
static int make_path(const char*prefix,const char*suffix,char*out,size_t cap){return snprintf(out,cap,"%s%s",prefix,suffix)>=(int)cap;}
int half_write_bands_npz_c(const char*prefix,int nk,int nb,const double*kpoints,const double*x,const double*eig,const double*shifted,const int64_t*npw,const double*smin,double vbm){
  char path[4096];if(make_path(prefix,".npz",path,sizeof path))return 1;entry_t e[7]={{"kpoints.npy"},{"x.npy"},{"eigenvalues_eV.npy"},{"eigenvalues_minus_vbm_eV.npy"},{"npw.npy"},{"overlap_min.npy"},{"vbm_eV.npy"}};size_t s2[2]={(size_t)nk,3},snk[1]={(size_t)nk},se[2]={(size_t)nk,(size_t)nb},one[1]={1};e[0].data=npy("<f8",1,2,s2,kpoints,sizeof(double)*nk*3,&e[0].size);e[1].data=npy("<f8",0,1,snk,x,sizeof(double)*nk,&e[1].size);e[2].data=npy("<f8",1,2,se,eig,sizeof(double)*nk*nb,&e[2].size);e[3].data=npy("<f8",1,2,se,shifted,sizeof(double)*nk*nb,&e[3].size);e[4].data=npy("<i8",0,1,snk,npw,sizeof(int64_t)*nk,&e[4].size);e[5].data=npy("<f8",0,1,snk,smin,sizeof(double)*nk,&e[5].size);e[6].data=npy("<f8",0,1,one,&vbm,sizeof(double),&e[6].size);for(int i=0;i<7;i++)if(!e[i].data)return 2;int rc=zip_store(path,e,7);for(int i=0;i<7;i++)free(e[i].data);return rc;}
int half_write_energy_npz_c(const char*prefix,int nk,int nb,const double*kpoints,const double*weights,const double*eig,const double*occ,int nf,const double*forces){
  char path[4096];if(make_path(prefix,".npz",path,sizeof path))return 1;entry_t e[5]={{"kpoints.npy"},{"weights.npy"},{"eigenvalues_eV.npy"},{"occupations.npy"},{"forces_eV_per_Angstrom.npy"}};size_t sk[2]={(size_t)nk,3},snk[1]={(size_t)nk},se[2]={(size_t)nk,(size_t)nb},sf[2]={(size_t)nf,3};e[0].data=npy("<f8",1,2,sk,kpoints,sizeof(double)*nk*3,&e[0].size);e[1].data=npy("<f8",0,1,snk,weights,sizeof(double)*nk,&e[1].size);e[2].data=npy("<f8",1,2,se,eig,sizeof(double)*nk*nb,&e[2].size);e[3].data=npy("<f8",1,2,se,occ,sizeof(double)*nk*nb,&e[3].size);e[4].data=npy("<f8",1,2,sf,forces,sizeof(double)*nf*3,&e[4].size);for(int i=0;i<5;i++)if(!e[i].data)return 2;int rc=zip_store(path,e,5);for(int i=0;i<5;i++)free(e[i].data);return rc;}
static void be32(unsigned char*p,uint32_t v){p[0]=v>>24;p[1]=v>>16;p[2]=v>>8;p[3]=v;}static uint32_t adler(const unsigned char*p,size_t n){uint32_t a=1,b=0;for(size_t i=0;i<n;i++){a=(a+p[i])%65521;b=(b+a)%65521;}return(b<<16)|a;}
static int chunk(FILE*f,const char*t,const unsigned char*d,size_t n){unsigned char b[4];be32(b,n);fwrite(b,1,4,f);fwrite(t,1,4,f);if(n)fwrite(d,1,n,f);unsigned char*q=malloc(n+4);if(!q)return 1;memcpy(q,t,4);if(n)memcpy(q+4,d,n);be32(b,crc32_bytes(q,n+4));free(q);fwrite(b,1,4,f);return 0;}
static void pixel(unsigned char*im,int w,int h,int x,int y,unsigned char r,unsigned char g,unsigned char b){if(x<0||x>=w||y<0||y>=h)return;unsigned char*p=im+3*(y*w+x);p[0]=r;p[1]=g;p[2]=b;}
static void line(unsigned char*im,int w,int h,int x0,int y0,int x1,int y1,unsigned char r,unsigned char g,unsigned char b){int dx=abs(x1-x0),sx=x0<x1?1:-1,dy=-abs(y1-y0),sy=y0<y1?1:-1,er=dx+dy;for(;;){pixel(im,w,h,x0,y0,r,g,b);if(x0==x1&&y0==y1)break;int e=2*er;if(e>=dy){er+=dy;x0+=sx;}if(e<=dx){er+=dx;y0+=sy;}}}
int half_write_bands_png_c(const char*prefix,int nk,int nb,const double*x,const double*shifted){
  enum{W=1200,H=800};char path[4096];if(make_path(prefix,".png",path,sizeof path))return 1;unsigned char*im=malloc(W*H*3),*raw=malloc((W*3+1)*H);if(!im||!raw)return 2;memset(im,255,W*H*3);double xmin=x[0],xmax=x[nk-1],ymin=0,ymax=0;for(int i=0;i<nk*nb;i++){if(shifted[i]<ymin)ymin=shifted[i];if(shifted[i]>ymax)ymax=shifted[i];}if(xmax<=xmin)xmax=xmin+1;if(ymax<=ymin)ymax=ymin+1;int l=80,r=W-30,t=30,b=H-60;line(im,W,H,l,t,l,b,40,40,40);line(im,W,H,l,b,r,b,40,40,40);int yz=b-(int)((0-ymin)/(ymax-ymin)*(b-t));for(int xx=l;xx<r;xx+=12)line(im,W,H,xx,yz,xx+6,yz,100,100,100);for(int band=0;band<nb;band++)for(int i=1;i<nk;i++){int x0=l+(int)((x[i-1]-xmin)/(xmax-xmin)*(r-l)),x1=l+(int)((x[i]-xmin)/(xmax-xmin)*(r-l));int y0=b-(int)((shifted[(i-1)+nk*band]-ymin)/(ymax-ymin)*(b-t)),y1=b-(int)((shifted[i+nk*band]-ymin)/(ymax-ymin)*(b-t));if(x1>x0)line(im,W,H,x0,y0,x1,y1,21,87,166);}size_t row=W*3+1,raw_n=row*H;for(int y=0;y<H;y++){raw[y*row]=0;memcpy(raw+y*row+1,im+y*W*3,W*3);}size_t blocks=(raw_n+65534)/65535,zcap=2+blocks*5+raw_n+4;unsigned char*z=malloc(zcap),*p=z;*p++=0x78;*p++=0x01;size_t off=0;while(off<raw_n){uint16_t n=(uint16_t)((raw_n-off)>65535?65535:(raw_n-off));int last=off+n==raw_n;*p++=last;*p++=n&255;*p++=n>>8;uint16_t nn=~n;*p++=nn&255;*p++=nn>>8;memcpy(p,raw+off,n);p+=n;off+=n;}uint32_t a=adler(raw,raw_n);be32(p,a);p+=4;FILE*f=fopen(path,"wb");if(!f)return 3;fwrite("\x89PNG\r\n\x1a\n",1,8,f);unsigned char ih[13];be32(ih,W);be32(ih+4,H);ih[8]=8;ih[9]=2;ih[10]=ih[11]=ih[12]=0;chunk(f,"IHDR",ih,13);chunk(f,"IDAT",z,p-z);chunk(f,"IEND",NULL,0);int rc=fclose(f);free(im);free(raw);free(z);return rc!=0;}
